default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: weather_project_development

test:
  <<: *default
  database: weather_project_test

production:
  <<: *default
  database: weather_project_production
