default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: weather_project_development
  username: root
  password:

test:
  <<: *default
  database: weather_project_test
  username: root
  password:

production:
  <<: *default
  database: weather_project_production
  username: weather_project
  password: <%= ENV['WEATHER_PROJECT_DATABASE_PASSWORD'] %>
